# Type stub for tsrkit_asm
from typing import Any

def assemble(code: str) -> bytes: ...
def disassemble(data: bytes) -> str: ...

class Assembler:
    def __init__(self) -> None: ...
    def assemble(self, code: str) -> bytes: ...
